server:
  port: 8083
  servlet:
    context-path: /statistics

spring:
  application:
    name: statistic-service

  datasource:
    url: jdbc:h2:mem:statistic_db

  h2:
    console:
      enabled: true

  kafka:
    bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: statisticGroup
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.nvminh162.statistic.model.Statistic
        spring.json.type.mapping: statistic:com.nvminh162.statistic.model.Statistic