server:
  port: 8083
  servlet:
    context-path: /statistics

spring:
  application:
    name: statistic-service

  datasource:
    url: jdbc:h2:mem:statistic_db

  h2:
    console:
      enabled: true

  kafka:
    bootstrap-servers: kafka-1:29092,kafka-2:29093,kafka-3:29094
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.nvminh162.statistic.model.Statistic
    listener:
      ack-mode: batch